FROM public.ecr.aws/docker/library/node:19.0-bullseye-slim AS builder

WORKDIR /app

COPY ./app/package.json .
RUN npm install yarn

COPY app .

RUN yarn \
 && NODE_ENV=production yarn build

FROM public.ecr.aws/docker/library/node:19.0-bullseye-slim

WORKDIR /app

COPY --from=builder app .

CMD ["yarn", "start"]
